Linked: (/home/weety/tart5/devel/.private/face_tracker/share/face_tracker/cmake/face_trackerConfig-version.cmake, /home/weety/tart5/devel/share/face_tracker/cmake/face_trackerConfig-version.cmake)
Linked: (/home/weety/tart5/devel/.private/face_tracker/share/face_tracker/cmake/face_trackerConfig.cmake, /home/weety/tart5/devel/share/face_tracker/cmake/face_trackerConfig.cmake)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/stages.py", line 174, in function_proxy
    return function(logger, event_queue, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/jobs/catkin.py", line 291, in link_devel_products
    source_hash = md5(open(os.path.realpath(source_file)).read().encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 74: ordinal not in range(128)

Stage `symlink` failed with arguments:
  package: {'package_format': 2, 'exports': [], 'buildtool_export_depends': [], 'exec_depends': [], 'name': 'face_tracker', 'filename': '/home/weety/tart5/src/face_tracker/package.xml', 'replaces': [], 'version_abi': None, 'build_export_depends': [], 'doc_depends': [], 'test_depends': [], 'maintainers': [<catkin_pkg.package.Person object at 0x7f0b22d395d0>], 'version': '0.0.0', 'build_depends': [], 'urls': [], 'authors': [], 'licenses': ['TODO'], 'buildtool_depends': [<catkin_pkg.package.Dependency object at 0x7f0b22d4f950>], 'conflicts': [], 'description': u'The face_tracker package'}
  metadata_path: /home/weety/tart5/.catkin_tools/profiles/default
  devel_manifest_path: /home/weety/tart5/.catkin_tools/profiles/default/packages/face_tracker
  prebuild: False
  package_path: face_tracker
  dest_devel_path: /home/weety/tart5/devel
  source_devel_path: /home/weety/tart5/devel/.private/face_tracker
